name: cherry
description: Simple yet powerful, open-source SpaceX launch tracker.

version: 2.10.1+65

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ## Flutter SDK
  flutter:
    sdk: flutter

  ## Online
  dio: ^3.0.9
  flutter_email_sender: ^3.0.1
  flutter_web_browser: ^0.11.0
  launch_review: ^2.0.0

  ## Widgets
  add_2_calendar: ^1.4.0
  big_tip: ^1.1.1
  flutter_local_notifications: ^1.4.4+2
  flutter_map: ^0.10.1
  flutter_markdown: ^0.4.2
  flutter_swiper: ^1.1.6
  flutter_svg: ^0.18.0
  row_collection: ^0.2.4
  search_page: ^1.3.0
  sliver_fab: ^1.0.0

  ## Tools
  flutter_i18n: ^0.18.0
  google_fonts: ^1.1.0
  package_info: ^0.4.1
  provider: ^4.3.1
  quick_actions: ^0.4.0+6
  share: ^0.6.4+3
  shared_preferences: ^0.5.7+3
  system_setting: ^0.1.3
  clipboard: ^0.1.2+8

  cherry_components:
    git:
      url: git@github.com:jesusrp98/cherry_components.git

  ## Linter
  lint: ^1.2.0

dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5

flutter_native_splash:
  image: assets/icons/icon_splash.png
  color: "#151515"

flutter_icons:
  image_path: assets/icons/icon_app.png
  android: false
  ios: true

flutter:
  assets:
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true
